version: '3'
services:
    rabbitmq:
        build:
            context: .
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: pass
        ports:
            - 8080:15672
            - 5672:5672
            - 1883:1883