version: '3'
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: pass
        ports:
            - 8080:15672
            - 5672:5672